---
title: "Panola GA Bird Banding"
author: "Maya Lapp"
date: "12/13/2021"
output: pdf_document
---

```{r setup, include=FALSE}
# settings for this file
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# load packages 
library(tidyverse)
library(readxl)
library(lubridate)

# Note: **PPP** = "Potential problem point" in code if trying to run new data - this may be useful for Maya if she is trying to debug the code 
# TODO - things that still need to be completed by Maya
```

```{r params}
# This section contains parameters that you can change when you run the analysis

################ EXCEL DATA FILES ################ 
# Change these file names to match the most recent data files
# Usage note: the excel data files must be in the same folder as this Rmd file

# file name for banding data
band_file <- "All bands Dec 9 2021.xls"

# file name for recapture data
recap_file <- "All Recaps Dec 9 2021.xls"

# file name for the net-hours for each net
net_hr_file <- "net_hours_example.xlsx"

# file name for BPNH for each year
cumulative_file <- "pano_year_data.xlsx"

# Exporting data
# Usage note: Set this to "TRUE" to export BPNH data to excel files. Set this to "FALSE" if you just want to plots and do not want to save the data. Files will be saved as "MM-DD-YY_HHMMSS_data_[file_id].csv" - where file_id is "most caught species, "grassland species", or "my species" 
export_data <- FALSE 


################  PARAMETERS  YOU MAY WANT TO CHANGE ################ 
# the minimum number of observations of a species needed for that species to be included in the analysis
# Usage note: increase this to include fewer species; decrease this to include more species
min_obs <- 150 

# specific species of interest
# Usage note: change the species listed here if you are interested in creating a plot of one or more specific species 
my_species <- c("AMGO", "INBU") 


################  PARAMETERS  YOU PROBABLY WON'T CHANGE ################ 

# "Big" grassland species to be included in individual species analysis of grassland species  
# Usage note: do not change this unless you want to analyze different grassland species
key_grasslands <- c("BLGR", "COYE", "EABL", "FISP", "INBU", "SAVS", "SWSP", "YBCH")

# All grassland species 
# Usage note: do not change this unless you want to add/remove grassland species to the joint analysis of all grassland species 
all_grasslands <- c(key_grasslands, "AMKE", "BOBO", "GRSP", "HESP", "LESP", "LISP", "LOSH", "EAKI", "PRWA", "WISN", "SEWR", "VESP", "YEWA")

# location for analysis
# Usage note: do not change this unless you're interested in a different location (not panola)
loc <- "PANO"
```


```{r load_data, warning=FALSE}
# read in files with banding data and recapture data 
recap_data <- read_excel(recap_file) %>% mutate(recap = TRUE)
band_data <- read_excel(band_file) %>% mutate(recap = FALSE) %>% 
  rename(Net = `Net/box`)

# data cleaning for banding data
all_data <- recap_data %>% 
  full_join(band_data)  %>% # join recap and band data 
  filter(Location == loc) %>% 
  mutate(Time = str_split_fixed(Time, " ", 2)[,2]) %>% # only keep time (not [incorrect] date) **PPP**
  rename(banding_date = `Banding Date`, recapture_date = `Recapture Date`, how_captured = `How Captured`, band_number = `Band Number`, wing_chord = `Wing Chord`) %>%  # rename columns without spaces
  mutate(net_number = as.factor(as.numeric(Net)), Species = as.factor(Species)) %>% # only keep number for nets; change species to factor 
  filter(grepl("net", tolower(how_captured), fixed = TRUE)) %>%  # select only birds that were capture via mist nets - note, this will select only (and all) observations with the word "net" in the how_captured column (lowercase/uppercase does not matter)
  mutate(obs_date = coalesce(recapture_date, banding_date)) %>% # create variable for data of observation (banding date if first time captured, otherwise recapture date)
  mutate(obs_yr = as.numeric(format(obs_date, "%Y"))) %>% # create variable for year of observation 
  mutate(Species = as.character(Species)) %>% 
  mutate(Species = ifelse(Species %in% c("WPWA", "YPWA"), "PAWA", Species)) %>%  # group western palm warbler and yellow palm warbler as "PAWA"
  mutate(Species = ifelse(Species %in% c("TRFL", "WIFL"), "TRFL/WIFL", Species)) %>%   # trails flycatcher and willows flycatcher as "TRFL/WIFL"
  mutate(grassland = Species %in% all_grasslands) # create boolean of whether each bird is a grassland species or not

 
# read in year-cumulative data (ie net hours and unbanded captures)
cumulative_data <- read_excel(cumulative_file) 

# read in and clean net-hour data 
net_hr_data <- read_excel(net_hr_file) %>% 
  mutate(Date = as.Date(as.numeric(Date), origin = "1899-12-30")) %>% # keep date from excel file
  filter(!is.na(Date)) %>%  # delete rows with no date
  gather(key= "net", value = "hrs", -Date) %>% # gather so there is one row for each net for each date
  mutate(hrs = as.numeric(hrs), year = format(Date, "%Y"))

# calculate total number of net-hrs per year
#cumulative_data = net_hr_data %>% 
#  group_by(year)%>% 
#  summarize(hrs = sum(hrs, na.rm = TRUE))

# calculate total number of net-hrs per net
net_hrs_per_net <- net_hr_data %>% 
  group_by(year, net)%>% 
  summarize(hrs = sum(hrs, na.rm = TRUE))
```

```{r funs}
# functions for calculating stats and plotting

# calculate BPNH for specific set of species 
# input: 
# my_spec - a list of the species we are interested in 
# file_id - optional input - added as a label to the end of the file if exporting bpnh data to csv
# output: BPNH for each year for each species in my_spec 
calc_bpnh <- function(my_spec, file_id = ""){
  out <- all_data %>%  
    filter(Species %in% my_spec) %>% 
    group_by(obs_yr, Species) %>% 
    summarize(tot_birds = n()) %>%  # number of banded/recaptured birds for each year
    left_join(cumulative_data, by = c("obs_yr" = "year") ) %>% # add net-hours and released bird data
    select(-unbanded_captures) %>% #drop column
    mutate(bpnh = tot_birds/net_hrs) #calculate birds per net hour 
  
  if(export_data){
    export_df(out %>%  select(-net_hrs), file_id = paste("_bpnh", file_id, sep = ""))
  }
  
  out
}

# export data to csv file - file starts with system date and time to make sure it doesn't overwrite another exported file 
# inputs: 
# df - dataframe 
# file_id - (optional) string to add to file name to indicate what is in it 
# out: exports df to csv file named "MM-DD-YYY_HHMMSS_data_file_id.csv" (e.g. 02-02-2022_112020_data_bpnh_grassland.csv")
export_df <- function(df, file_id = ""){
  datetime <- gsub(":", "", Sys.time())
  datetime <- gsub(" ", "_", datetime)
  write_excel_csv(df , file = paste(datetime, "_data", file_id, ".csv", sep = ""))
}

# plot BPNH for all species in bpnh_df
# input: bpnh_df - dataframe of BPNH for each year for a various species 
# output: one plot for each species of BPNH over time
plot_bpnh <- function(bpnh_df){
  my_species = unique(bpnh_df$Species)
  
  for(spec_i in my_species){
    
      mod <- lm(bpnh ~ obs_yr, data = bpnh_df %>% filter(Species == spec_i)) #create linear model
      mod_summary <- summary(mod)
      pval <- mod_summary$coefficients[ , 4][2] # get the p value for the year coefficient 
      #r <- s$r.squared 

  p <- bpnh_df %>% filter(Species == spec_i) %>% 
    ggplot(aes(x = obs_yr, y = bpnh)) +
    geom_point() + 
    geom_smooth(method=lm, se = FALSE) + # add linear trendline 
    ggtitle(paste(spec_i, " (p = ", round(pval,3), ")", sep = "")) + 
    xlab("Year") + 
    ylab("Birds per net hour (BPNH)")+ 
    theme_bw()
  
  print(p)
}
}
```
# Plot BPNH for all birds and grassland birds 

```{r cum_bpnh}
# calculate BPNH for all birds caught each year - add in unbanded captures 
bpnh_data <- all_data %>%  
  group_by(obs_yr) %>% 
  summarize(tot_birds = n()) %>%  # number of banded/recaptured birds for each year
  left_join(cumulative_data, by = c("obs_yr" = "year") ) %>% # add net-hours and released bird data
  mutate(tot_birds = tot_birds + unbanded_captures) %>% # include captured but released birds in tot_birds
  select(-unbanded_captures) %>% #drop column
  mutate(bpnh = tot_birds/net_hrs)  #calculate birds per net hour 

# calculate BPNH for grassland birds each year 
bpnh_grass_data <- all_data %>%  
  group_by(obs_yr, grassland) %>% 
  summarize(tot_birds = n()) %>%  # number of banded/recaptured birds for each year
  left_join(cumulative_data, by = c("obs_yr" = "year") ) %>% # add net-hours and released bird data
  select(-unbanded_captures) %>% #drop column
  mutate(bpnh = tot_birds/net_hrs) #calculate birds per net hour 

# combine all birds and grassland birds dfs into one 
bpnh_data <- bpnh_data %>%  bind_rows(bpnh_grass_data) %>% 
  mutate(descr = ifelse(is.na(grassland), "all birds", ifelse(grassland, "grassland", "not grassland"))) %>% 
  select(-grassland)

# get pvalue for year coefficient of linear regression for all birds
mod <- lm(bpnh ~ obs_yr, data = bpnh_data %>% filter(descr == "all birds"))  #create linear model
mod_summary <- summary(mod)
pval_allBirds <- mod_summary$coefficients[ , 4][2] # get the p value for the year coefficient 

# get pvalue for year coefficient of linear regression for grassland birds 
mod <- lm(bpnh ~ obs_yr, data = bpnh_data %>% filter(descr == "grassland"))  #create linear model
mod_summary <- summary(mod)
pval_grassland <- mod_summary$coefficients[ , 4][2] # get the p value for the year coefficient 


# plot of BPNH over years 
bpnh_data %>% 
  filter(descr != "not grassland") %>% 
  mutate(descr = ifelse(descr == "all birds", paste("all birds (p = ", round(pval_allBirds, 3), ")", sep = ""), paste("grassland (p = ", round(pval_grassland, 3), ")", sep = ""))) %>% # add p-value to plot titles 
  ggplot(aes(x = obs_yr, y = bpnh)) +
  geom_point() + 
  geom_smooth(method=lm, se = FALSE) + # add linear trendline 
  facet_wrap(~descr) + 
  xlab("Year") + 
  ylab("Birds per net hour (BPNH)")+ 
  theme_bw()


```


# Plot BPNH for species with more than `r min_obs` observations 
```{r most_obs}
# Create a list of all birds with over "min_obs" observations 

most_observed_birds <- all_data %>% 
  group_by(Species) %>% 
  summarize(tot_birds = n()) %>% 
  arrange(-tot_birds) %>% 
  filter(tot_birds > min_obs) 

most_observed_birds <- unique(most_observed_birds$Species)


calc_bpnh(most_observed_birds, file_id = "_mostCaughtSpecies") %>% plot_bpnh() 
```


# Plot BPNH for key grassland species

```{r} 
calc_bpnh(key_grasslands, file_id = "_grasslands") %>% plot_bpnh() 

```

# Plot BPNH for selected species of interest

Currently selected species: `r my_species` 

```{r}
calc_bpnh(my_species, file_id = "_mySpecies") %>% plot_bpnh() 
```


```{r perc_species, include = FALSE}
#Looking at percentages of species in nets - don't run this for now 

# calculate total number of birds caught by each net
birds_per_net <- all_data %>% 
  group_by(net_number) %>% 
  summarize(tot_birds= n()) %>% # total number of birds caught in each net
  filter(tot_birds > 1) # ignore nets with only one observation - probably typo **PPP** 

# calculate total number of birds caught by each net for each year 
birds_per_net_per_year <- all_data %>% 
  group_by(net_number, obs_yr) %>% 
  summarize(tot_birds= n()) #%>% # total number of birds caught in each net each year
#  filter(tot_birds > 1) # ignore nets with only one observation - probably typo **PPP** 

# calculate percent of each species for each net 
net_spec <- all_data %>% 
  group_by(net_number, Species) %>% 
  summarize(num_birds = n()) %>% 
  left_join(birds_per_net) %>% 
  mutate(perc_species = num_birds/tot_birds*100) 
net_spec

# calculate percent of each species for each net for each year 
net_spec_yr <- all_data %>% 
  group_by(net_number, Species, obs_yr) %>% 
  summarize(num_birds = n()) %>% 
  left_join(birds_per_net_per_year) %>% 
  mutate(perc_species = num_birds/tot_birds*100)
net_spec_yr

# create dataframes to export to csv files
net_spec_export <- net_spec %>% select(-tot_birds)
net_spec_yr_export <- net_spec_yr %>% select(-tot_birds)

#export dataframes to csv files named by current date 
write_excel_csv(net_spec_export, file = paste(Sys.Date(), "_net_percSpecies", ".csv", sep = ""))
write_excel_csv(net_spec_yr_export, file = paste(Sys.Date(), "_net_percSpecies_yr", ".csv", sep =""))

```


```{r notes, include = FALSE}
# NOTES FROM CHARLIE 
# Big ones: Blue Grosbeak,Common Yellowthroat, Eastern Bluebird, Field Sparrow, Indigo Bunting, Savannah Sparrow, Swamp  Sparrow, and Yellow-breasted Chat 
# 
# Additional: American Kestrel, Bobolink, Grasshopper Sparrow, Henslow's Sparrow, LeConte's Sparrow, Lincoln's Sparrow, Loggerhead Shrike, Eastern Kingbird, Prairie Warbler, Wilson's Snipe, Sedge Wren, Vesper Sparrow and Yellow Warbler 
# 
# Western Palm Warbler and Yellow Palm Warbler are 2 subspecies of Palm Warbler and can be lumped for analysis.
# 
# Trail's Flycatcher and Willow Flycatcher are more or less the same species and can be lumped.
# 
# Eastern Phoebe is a WEIRD one.  It's not a grassland bird, but we catch loads of them - and they are almost all recently-fledged juveniles.  And we almost never recapture them.  I really need an analysis of them, but not sure how to handle it.
```

